BEGIN;

DROP TABLE IF EXISTS CARTS, PRODUCTS, CLIENT CASCADE;

CREATE TABLE CLIENT(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    AVATAR TEXT DEFAULT 'https://www.seekpng.com/png/detail/110-1100707_person-avatar-placeholder.png',
    ROLE VARCHAR(5) CHECK ( ROLE IN ('ADMIN', 'USER')) DEFAULT 'USER'
);

CREATE TABLE PRODUCTS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DOUBLE PRECISION NOT NULL,
    STOCK INT NOT NULL DEFAULT 1,
    CATEGORY VARCHAR(50) NOT NULL DEFAULT 'Uncategorized',
    IMAGE TEXT NOT NULL DEFAULT 'https://erasmusnation-com.ams3.digitaloceanspaces.com/woocommerce-placeholder.png',
    GALARY TEXT ARRAY[3]
);

CREATE TABLE CARTS(
    ID SERIAL PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CLIENT_ID INT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    CONSTRAINT CLINT_ID_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE
);

COMMIT;